### ISSUE TITLE
Getting the user's name?

### ISSUE THREAD

**Issue by wrunk** [Timothylock/go-signin-with-apple#13]
Hello and thanks for this repo! The example is working great now except I cannot seem to get the user's name back (sounds like this is possible with apple - if only on the first request per user). Any idea on how this can be done? Happy to work on a PR if so, thanks!

**Comment by Timothylock** [comment]
Hey @wrunk ! Thanks for bringing that up. We originally ran into that issue at my workplace over a year ago and at that time the endpoint did not return that user info (even on the first request). We got around that by using the internal ios libraries on our clients to get the names. However if the solution exists today and you manage to make it work, send a PR over and we'll get that merged :)
