### ISSUE TITLE
[JWT:002] cannot decode the parts

### ISSUE THREAD

**Issue by Tobi696** [Timothylock/go-signin-with-apple#22]
I get the error `[JWT:002] cannot decode the parts` running the code you provided in the examples.

**Comment by sauceman40** [comment]
> I get the error `[JWT:002] cannot decode the parts` running the code you provided in the examples.

+1 - seeing the same error

**Comment by sauceman40** [comment]
@Tobi696 if you're still running into that error -- I was passing the IdentityToken from Apple to VerifyAppToken, not the AuthorizationCode. It works correctly for me when i pass authorization code.

@Timothylock it may be helpful to update the code examples when you get the chance. It currently says `the_token_to_validate` in the Code parameter, which was a bit confusing to me.

**Comment by Timothylock** [comment]
Thanks @sauceman40! I have gone ahead and updated the documentation to make it more clear that it should be the authorization code. I can see how the naming of the value may have been misleading and hopefully the new changes makes it clearer. 

@Tobi696 are you still having an issue after correcting it?

**Comment by sauceman40** [comment]
Sure thing @Timothylock! Thanks for the quick response -- and awesome library you've created. Very much appreciated!

**Comment by Timothylock** [comment]
Closing as stale.
