### ISSUE TITLE
Revoke token

### ISSUE THREAD

**Issue by txbrown** [Timothylock/go-signin-with-apple#27]
Apple requires apps to conform with "right to forget" - users can delete their account.
As part of this process, tokens used to sign/signup with apple should be revoked to fully disassociate a user with an app.

See more details [here](https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens)

At the moment this library does not support this feature.

I am raising this issue here first but a member of our team at midicircuit.com should be able to raise a PR with unit tests for this soon.

**Comment by tiagoinacio** [comment]
PR: https://github.com/Timothylock/go-signin-with-apple/pull/28

**Comment by prvaghasiya** [comment]
Hello, 
Any tentative release date for this PR?

**Comment by Timothylock** [comment]
Apologies for the delay @txbrown , @tiagoinacio , @prvaghasiya . Was on vacation. Taking a look now!

**Comment by Timothylock** [comment]
Merged https://github.com/Timothylock/go-signin-with-apple/pull/28 . Thanks for the contribution!
