### ISSUE TITLE
Go 1.20

### ISSUE THREAD

**Issue by mdzigurski** [Timothylock/go-signin-with-apple#37]
Hello,

Is it possible to downgrade the Go version in go.mod from Go 1.22 to Go 1.20? We are still on Go 1.20, and the package doesn't compile in our project because it requires Go 1.22. 

Thank you

**Comment by Timothylock** [comment]
Hey! Let me take a look into this

**Comment by Timothylock** [comment]
Just crafted a new release - https://github.com/Timothylock/go-signin-with-apple/releases/tag/v0.2.2 

I dropped it down to 1.18 since thats the highest version required by the dependencies of this project while still working as intended

**Comment by mdzigurski** [comment]
@Timothylock Thank you that worked. I can build my project using the v0.2.3.

**Comment by Timothylock** [comment]
Glad to hear! Thanks for catching that!
