### ISSUE TITLE
apple returned an error: invalid_request

### ISSUE THREAD

**Issue by iusn** [Timothylock/go-signin-with-apple#8]
hi:
i have a problem
i want to verification app login
 clientID i set  Services ID or app id
the apple service always return
"invalid_request"
can you help me
thank you
<img width="459" alt="Screen Shot 2020-02-16 at 2 07 47 AM" src="https://user-images.githubusercontent.com/11364258/74593086-c88e2f80-5062-11ea-892e-be990619caaf.png">

**Comment by Timothylock** [comment]
Apple is very vague about the errors. The error you are seeing is from their servers. Did you make sure your keys/certificates are assigned to the correct app in Apple Connect? Also make sure sign in with apple checkbox is enabled. This is a good guide to making sure everything is hooked up correctly: 

https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple

**Comment by iusn** [comment]
> Apple is very vague about the errors. The error you are seeing is from their servers. Did you make sure your keys/certificates are assigned to the correct app in Apple Connect? Also make sure sign in with apple checkbox is enabled. This is a good guide to making sure everything is hooked up correctly:
> 
> https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple

thank you
